name: Deploy Supabase

on:
  push:
    branches: [ main ]
    paths:
      - '**'  # Watch all files in this repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Initialize Supabase
        run: |
          supabase init
          
      - name: Setup Production Config
        run: |
          echo '${{ secrets.SUPABASE_PROD_CONFIG }}' | base64 -d > supabase/config.toml
          
      - name: Deploy Migrations
        run: |
          TMPFILE=$(mktemp)
          echo "$DB_PASSWORD" > "$TMPFILE"
          supabase link --project-ref $PROJECT_ID --password-stdin < "$TMPFILE"
          rm -f "$TMPFILE"
          supabase db push
          
      - name: Cleanup
        if: always()  # Run even if previous steps fail
        run: |
          rm -f supabase/config.toml 