name: Deploy Supabase

on:
  push:
    branches: [ main ]
    paths:
      - '**'  # Watch all files in this repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Deploy Migrations
        run: |
          # Backup development config if it exists
          [ -f config.toml ] && cp config.toml config.dev.toml || true
          
          # Use production config
          cp config.prod.toml config.toml
          
          # Deploy
          supabase link --project-ref $PROJECT_ID
          supabase db push
          
          # Restore development config if it existed
          [ -f config.dev.toml ] && cp config.dev.toml config.toml || true 