name: Deploy Supabase

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Initialize Supabase
        run: |
          supabase init
          
      - name: Setup Production Config
        run: |
          echo '${{ secrets.SUPABASE_PROD_CONFIG }}' | base64 --decode > supabase/config.toml
          
      - name: Deploy Migrations
        run: |
          supabase link --project-ref "$PROJECT_ID"
          supabase db push
          
      - name: Cleanup
        if: always()  # Run even if previous steps fail
        run: |
          rm -f supabase/config.toml 